---
- name: Converge
  hosts: all
  vars:
    users:
      - name: root
        fullname: "Root"
        home: /root
        email: root@molecule.test
    github_repo_name:
      - stiliajohny/stiliajohny.github.io
    destination: "{{ users[0].home }}/"
  tasks:
    - name: "Include role ansible-role-git"
      include_role:
        name: ansible-role-git
