---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: "molecule-ubuntu1804"
    image: "geerlingguy/docker-ubuntu2004-ansible"
    command: ""
    privileged: true
    pre_build_image: true
  - name: "molecule-centos7"
    image: "geerlingguy/docker-centos7-ansible"
    command: ""
    privileged: true
    pre_build_image: true
  - name: "Archlinux"
    image: "archlinux"
    command: ""
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  # options:
  #   become: true
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
